export const USER_LOGIN = 'USER_LOGIN';
export const USER_EDIT_PROFILE_TOGGLE = 'USER_EDIT_PROFILE_TOGGLE';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const MENULIST_FETCH = 'MENULIST_FETCH';

export const ACCOUNTS_FETCH = 'ACCOUNTS_FETCH';
export const ACCOUNTS_ADD_TOGGLE = 'ACCOUNTS_ADD_TOGGLE';
export const ACCOUNTS_ADD = 'ACCOUNTS_ADD';
export const ACCOUNTS_EDIT_TOGGLE = 'ACCOUNTS_EDIT_TOGGLE';
export const ACCOUNTS_UPDATE = 'ACCOUNTS_UPDATE';
export const ACCOUNTS_DELETE = 'ACCOUNTS_DELETE';