export const USER_LOGIN = 'USER_LOGIN';
export const USER_EDIT_PROFILE_TOGGLE = 'USER_EDIT_PROFILE_TOGGLE';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const MENULIST_FETCH = 'MENULIST_FETCH';

export const ROLELIST_FETCH = 'ROLE_CAN_MANAGE_FETCH';

export const PRESCRIPTIONS_FETCH = 'PRESCRIPTION_FETCH';
export const PRESCRIPTIONS_SELECT = 'PRESCRIPTION_SELECT';
export const PRESCRIPTIONS_ADD_PILLSTORE = 'PRESCRIPTIONS_ADD_PILLSTORE';

export const ACCOUNTS_FETCH = 'ACCOUNTS_FETCH';
export const ACCOUNTS_ADD_TOGGLE = 'ACCOUNTS_ADD_TOGGLE';
export const ACCOUNTS_ADD = 'ACCOUNTS_ADD';
export const ACCOUNTS_EDIT_TOGGLE = 'ACCOUNTS_EDIT_TOGGLE';
export const ACCOUNTS_UPDATE = 'ACCOUNTS_UPDATE';
export const ACCOUNTS_DELETE = 'ACCOUNTS_DELETE';

export const PILLSTORES_FETCH = 'PILLSTORES_FETCH';
export const PILLSTORES_ADD_TOGGLE = 'PILLSTORES_ADD_TOGGLE';
export const PILLSTORES_ADD = 'PILLSTORES_ADD';
export const PILLSTORES_EDIT_TOGGLE = 'PILLSTORES_EDIT_TOGGLE';
export const PILLSTORES_UPDATE = 'PILLSTORES_UPDATE';
export const PILLSTORES_DELETE = 'PILLSTORES_DELETE';

export const PILLS_FETCH = 'PILLS_FETCH';
export const PILLS_ADD_TOGGLE = 'PILLS_ADD_TOGGLE';
export const PILLS_ADD = 'PILLS_ADD';
export const PILLS_EDIT_TOGGLE = 'PILLS_EDIT_TOGGLE';
export const PILLS_UPDATE = 'PILLS_UPDATE';
export const PILLS_DELETE = 'PILLS_DELETE';